### ISSUE TITLE
subversion-perl not found on CentOS

### ISSUE THREAD

**Issue by pungoyal** [geerlingguy/ansible-role-git#10]
`subversion-perl` is not a part of the standard centos distribution. The ansible role should not assume that it would be available.

**Comment by acrewdson** [comment]
+1

**Comment by geerlingguy** [comment]
Strangely... it seems like it's working okay in the Travis CI tests, which are based on the official centos7 Docker image. Also see: https://github.com/geerlingguy/ansible-role-git/pull/31

**Comment by acrewdson** [comment]
@geerlingguy FWIW I was having the problem on CentOS 6.
