### ISSUE TITLE
This project shows a buildbutton in galaxy. How does it work?

### ISSUE THREAD

**Issue by 030** [geerlingguy/ansible-role-git#12]
I have seen that multiple projects that were created by you contain a travis badge. [I am trying based on documentation and examples to implement it as well](http://serverfault.com/questions/795370/why-is-the-travis-badge-not-assigned-to-the-role-in-ansible-galaxy), but it fails and I do not understand why? Could you explain how it works?

**Comment by geerlingguy** [comment]
Please see: http://serverfault.com/a/795399/15673

Thanks!
