### ISSUE TITLE
CentOS 7: git_install_from_source alone doesn't work anymore

### ISSUE THREAD

**Issue by lukyanov** [geerlingguy/ansible-role-git#18]
On CentOS 7 the dependency `gettext-devel` now installs git package. So even if I set `git_install_from_source: true`, it doesn't help as the git is already installed at the time when the check `Get installed version` in `install-from-source.yml` happens.

The workaround is:
```
git_install_from_source: true
git_reinstall_from_source: true
```

**Comment by geerlingguy** [comment]
D'oh! I'm not 100% sure how we could work around that, short of setting an indicator in /etc/ or somewhere else to check if source install has been completed before.

**Comment by alok15ee** [comment]
I did try @lukyanov your suggestion but it looks like skipping the whole process. In fact I made sure that install-from-source.yml is always running by remove the above condition. Still it seems to be skipping all the tasks.

**Comment by flotho** [comment]
really sad news.
Could it be a workaround to add an alternative via update-alternative : something loke http://stackoverflow.com/questions/12787757/how-to-use-the-command-update-alternatives-config-java

**Comment by flotho** [comment]
@geerlingguy ,
here is a proposal for the workflow :
* If installed from source is true then install from source in a "usr" folder
* check if https://linux.die.net/man/8/update-alternatives already set
* if not create / install the config and declare the installed from source executable as main app for the config

regards

**Comment by karlwbrown** [comment]
Hi, I ran into this same issue.
If I set the variables as follows:
git_install_from_source: true
git_install_from_source_force_update: true
git_version: "2.14.1"

It will install/build the updated git version. However, the old git package is still installed (but I supposed partially overwritten by the build-from-source), which may cause issue with future package updates, etc. Any hints on how to get around this circular dependency?

**Comment by geerlingguy** [comment]
This role is intended mainly to help set up a new server or container, and things like switching between active versions / installation methods are usually one-time changes, and I'd rather that be the responsibility of the upstream playbook (e.g. if you used package install before, add a task to your playbook like `- package: name=git state=absent`).

Also, in local testing today it seems source install works fine in Travis CI testing and locally in both Vagrant and Docker, so I'm closing this issue for now unless we can get a provable set of conditions that fails to build/install Git on CentOS 7.
