### ISSUE TITLE
Git did not update to latest version

### ISSUE THREAD

**Issue by dqlopez** [geerlingguy/ansible-role-git#21]
I have the following on config:

```
---
git_install_from_source: true,
git_install_from_source_force_update: true,
git_version: "2.12.2"
```
The provision went well without error, but when I checked `git --version` on guest it still says `git version 2.7.4`.

I'm on:
`Linux ubuntu-xenial 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`.

What could I've missed?

**Comment by geerlingguy** [comment]
@dqlopez - Did you already have Git installed from system packages prior to using this role in a playbook?

**Comment by dqlopez** [comment]
Yes I do.

**Comment by geerlingguy** [comment]
In that case, you would need to uninstall the packaged version, then run a playbook using this role. The role presumes it's being run on a fresh install of a minimal OS, and won't actively remove Git from a computer where it's already set up.

**Comment by dwcaraway** [comment]
had the same issue, had to have git installed for ansible local to pull the ansible galaxy `geerlingguy.git` using `vagrant`, but centos yum installed  git version 1.8, the `geerling.guy` role didn't update git to the desired version.

My workaround was to add a `pre_tasks:` in my `playbook.yml`:

```yaml
pre_tasks:
    - name: remove git before geerlinguy.git
       package: "name=git state=absent"

roles:
    - geerlingguy.git
```

I think this issue can be closed

**Comment by geerlingguy** [comment]
@dwcaraway - That's a perfect fix! Thanks for posting it. Agreed, this can be closed as the role 'works as designed' as I don't want to add complicated logic to try to detect versions and upgrade or downgrade at will (unless maybe doing source install).
