### ISSUE TITLE
Fedora24 support?

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-git#22]
Just running a test via your Ansible role on your Docker image for Fedora24 and this came up.

I'm under the assumption this is a relatively easy fix, and it is outside of the scope of support for this role - so I'm not exactly sure how you feel about it.

````
"msg": "Failed to find handler for \"/root/git-2.9.3.tar.gz\". Make sure the required command to extract the file is installed. Commands \"gtar\" and \"tar\" not found. Command \"unzip\" not found."
````

**Comment by geerlingguy** [comment]
The role is currently passing with Fedora 24: https://github.com/geerlingguy/ansible-role-git/blob/master/.travis.yml#L20-L22 — see result: https://travis-ci.org/geerlingguy/ansible-role-git/builds/217682100

The base Docker image I'm using likely already has `unzip` installed. You should be able to install it with `dnf -y install unzip`, or in Ansiblese:

```yaml
- name: Install unzip.
  package: name=unzip state=present
```

**Comment by fubarhouse** [comment]
@geerlingguy 

I note that now, perhaps I'm encountering this problem because I'm building from source?

The example test with your fedora24 image was not done building from source.

Again I'm happy if you aren't interested here, but even installing unzip as a pre-execution task doesn't seem to get around this.

Apologies, I should have noted my configuration earlier.

**Comment by fubarhouse** [comment]
As a result to PR #25, this will now be closed.
This PR has benefited my roles which use your role for testing a great deal already - thank you :)
