### ISSUE TITLE
Make dependencies configurable.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/ansible-role-git#24]
Sup Jeff!

For the purposes of adding this role into my own playbooks for testing on unsupported architectures such as Ubuntu 12.10, 13.04, 14.10, 15.10, would you consider making the dependency lists optionally configurable so that when defined the role won't cause an error when a particular package cannot be found by the package manager?

My interim solution is to basically remove your role in these edge cases in favour of something else - what that is exactly is yet to be determined - or I could fork this one and do that myself despite not wanting to.

Kind regards,
Karl

**Comment by geerlingguy** [comment]
Do you mean the role dependencies? (e.g. https://github.com/geerlingguy/ansible-role-git/blob/master/meta/main.yml#L2), or a list of default packages that are installed (e.g. the configurable `git_packages` var, https://github.com/geerlingguy/ansible-role-git/blob/master/defaults/main.yml#L8-L10)?

**Comment by fubarhouse** [comment]
The actual dependencies of the installation.

For example, the package `libcurl4-gnutls-dev` causes the error `No package matching 'libcurl4-gnutls-dev' is available` on Ubuntu 15.10.

I'll draft up a PR :)

**Comment by fubarhouse** [comment]
Tests for this are passing, so I'll create the PR.
* https://travis-ci.org/fubarhouse/ansible-role-git/builds/242635864

**Comment by geerlingguy** [comment]
Thanks! I've left a few notes, but like the idea a lot!

**Comment by fubarhouse** [comment]
As a result of #25 this can now be closed.

You might be interested that I've now got this working on the following:
* Ubuntu 12.04
* Ubuntu 12.10
* Ubuntu 13.04
* Ubuntu 13.10
* Ubuntu 14.04
* Ubuntu 14.10
* Ubuntu 15.04
* Ubuntu 15.10
* Ubuntu 16.04
* Ubuntu 16.10
* Ubuntu 17.04
* Ubuntu 17.10
* CentOS6
* CentOS7
* Debian 7
* Debian 8
* Debian 9
* Redhat24
* Redhat25
* Redhat26

This paves a much easier path (without adopting more projects) for all of my roles to have this level of certified automated testing. So thank you very much, you've just saved me from more headaches!

**Comment by geerlingguy** [comment]
That's awesome! Glad I could help :)
