### ISSUE TITLE
Tag for version 1.2.2 is missing

### ISSUE THREAD

**Issue by ckonkel** [geerlingguy/ansible-role-git#26]
version 1.2.2 missing from tags

I use tags to lock in stability with my integration. Why was the tag removed? Whats the best way to implement and insure that it does not break my build because a version is no longer there?

**Comment by geerlingguy** [comment]
I don't think there was a 1.2.2, at least as far as I can tell... do you know where you found that version?

**Comment by geerlingguy** [comment]
Closing this for now; please let me know where you saw the 1.2.2 version as I can't see where it would've ever been set.
