### ISSUE TITLE
Centos 7 install from source slightly broken

### ISSUE THREAD

**Issue by BubbleSnap** [geerlingguy/ansible-role-git#28]
If installing from source, the ansible tasks are configured not to install the OS version of git. Instead the role will install the dependencies of git starting with gettext-devel.
The issue is that gettext-devel itself has a depedency on git, so will install git when gettext-devel is installed, so there is really no value in stopping the install of the git from OS in this case as it will be installed anyway.

This is usually not a problem at all, as Centos 7 base has an old version of git and the new version will always get downloaded and installed over it. However, when you have the ius repo enabled, git2u package is installed with the gettext-devel as a dependency as yum favours git2u over the base ok for providing git command (as it's more recent), meaning the subsequent build from source then fails typically. 

Should be a simple fix to make to guarantee reliability. I'll try something and push it back at some point.

**Comment by geerlingguy** [comment]
@BubbleSnap - I don't use IUS and it seems to not be as prevalent as a repo like epel, so pending any simple changes that could make this work with IUS/git2u, I'd rather close this for now.

**Comment by artm** [comment]
It isn't *slightly* broken, it won't install from source unless `git_install_from_source_force_update` is set to `true` because the task "Ensure git's dependencies are installed." installs OS git.
