### ISSUE TITLE
Please add configuration to use https rather than git:// native git addressing (to port 9148)

### ISSUE THREAD

**Issue by danryu** [geerlingguy/ansible-role-git#3]
This is a single line change which will allow all those working in typically restrictive corporate networks to access all git repos current inaccessible on port 9148.
This is what I adopted in my forked repo at https://github.com/danryu/ansible-role-git/blob/master/tasks/main.yml#L17

```
- name: configure git to use https and not native git protocol
  command: git config --global url."https://".insteadOf "git://"
```

and it works well in testing. Previous multi-hour hangs caused by composer trying to build drush by referencing dozens of github repos via git:// addresses are now avoided successfully.

Background provided in debugging outlined in https://github.com/geerlingguy/drupal-vm/issues/101

**Comment by geerlingguy** [comment]
This seems like a good improvement—but I'll leave it as a configurable option (e.g. using `when: git_use_https_instead_of_git_protocol`) so users can stick to `git://`/other protocols by default, and configure https if needed.

**Comment by danryu** [comment]
This seems fair :-)
