### ISSUE TITLE
Fails on CentOs7

### ISSUE THREAD

**Issue by vitas** [geerlingguy/ansible-role-git#34]
tried with default role as with following vars
  - role: geerlingguy.git
       git_install_from_source: false
       git_install_from_source_force_update: false

result
TASK [geerlingguy.git : Ensure git's dependencies are installed (RedHat).] *****
fatal: [default]: FAILED! => {"failed": true, "msg": "'git_install_from_source_dependencies' is undefined"}

**Comment by marcaddeo** [comment]
@vitas you may just have to update your version of Ansible. We had this issue as well on Ansible `2.2.2.0` and upgrading to `2.4.3.0`

**Comment by geerlingguy** [comment]
Hmm... likely related to https://github.com/geerlingguy/ansible-role-git/commit/ead753560f51e9415c8aa1b19b818881dd4e1b88#diff-408b14fc5cdd582965ea5d0aa0379e12 — which was added to fix some 2.4 incompatibilities, in a way I _thought_ was backwards compatible, but might not be entirely so.

Safer to jump to 2.4 anyways, then :/

**Comment by geerlingguy** [comment]
This change is now part of 2.0.0, which basically makes the role minimum dependency version 2.4.0.
