### ISSUE TITLE
Possibility to set GIT credentials

### ISSUE THREAD

**Issue by gitoutthere** [geerlingguy/ansible-role-git#4]
Is there a possibility to add the config to the role that sets git config --global user.name and user.email from vars?

**Comment by gitoutthere** [comment]
I added these to to my extra.yml
- name: Push global config file
  template:
    src: ../templates/drupalvm-gitconfig.j2
    dest: /etc/gitconfig

and in my drupalvm-gitconfig.j2
[user]
name = {{ git_username }}
email = {{ git_usermail }}

**Comment by geerlingguy** [comment]
This is now doable more easily/correctly using Ansible's new [`git_config` module](https://docs.ansible.com/ansible/git_config_module.html) (requires Ansible 2.1). See one example here: https://github.com/geerlingguy/ansible-role-git/pull/13 (for #3).
