### ISSUE TITLE
install_from_source causes repeated builds when prefix is not the default

### ISSUE THREAD

**Issue by rkm** [geerlingguy/ansible-role-git#51]
Hi, I'm using your playbook with the following vars:

```bash
git_version: 2.26.2
git_install_from_source: true
git_install_from_source_force_update: true
git_install_path: "/opt"
```

It looks as if the custom install prefix is causing the version check to fail on repeated runs.

I can probably submit a patch over the weekend if you like?

**Comment by viresh-contino** [comment]
Hi, i am using this and it fails:

`    - { role: geerlingguy.git, git_version: '2.21.0', git_install_from_source: true, git_install_from_source_force_update: true }`

what's the fix?

**Comment by rkm** [comment]
I think I've fixed the original issue [here](https://github.com/rkm/ansible-role-git/commit/ea883fed4a8c2756a588996d82127d0a3e3aafdf). Should I open a PR?

Not sure about your problem @viresh-contino, sorry!

**Comment by rkm** [comment]
`boop`

**Comment by rkm** [comment]
Here's an easy repro for the issue:

```shell
$ tail -n +1 Dockerfile playbook.yml vars/main.yml
==> Dockerfile <==
FROM centos:8

RUN : \
    && dnf -q -y update \
    && dnf -q -y install epel-release \
    && dnf -q -y install ansible git \
    && :

RUN mkdir /tmp/t
COPY playbook.yml /tmp/t/
COPY vars /tmp/t/vars

RUN : \
    && cd /tmp/t \
    && ansible-galaxy install geerlingguy.git --force \
    # && ansible-galaxy install git+https://github.com/rkm/ansible-role-git \
    && ansible-playbook playbook.yml \
    && ansible-playbook playbook.yml \
    && :

==> playbook.yml <==
- hosts: localhost
  become: true
  tasks:
    - name: Include vars
      include_vars: vars/main.yml
    - name: Run geerlingguy.git
      include_role:
        name: geerlingguy.git
        # name: ansible-role-git

==> vars/main.yml <==
git_version: 2.30.0
git_install_from_source: true
git_install_from_source_force_update: true
git_install_path: "/opt"
```

Building the Dockerfile results in git being built twice, since the version built in the initial run is not detected.

I believe the patch I suggested in #52 addresses this, which can be tested by switching the comments in the above Dockerfile and playbook.

**Comment by rkm** [comment]
`boop`

**Comment by rkm** [comment]
ping

**Comment by rkm** [comment]
`boop`

**Comment by rkm** [comment]
boop
